name: xignature_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_pdfview: ^1.2.7
  file_picker: ^5.3.0
  signature: any
  syncfusion_flutter_pdf: any
  syncfusion_flutter_pdfviewer: any
  path_provider: any
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

